BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `SubCategory` (
	`id`	INTEGER NOT NULL UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);
INSERT INTO `SubCategory` (id,name) VALUES (1,'Desktop CPU'),
 (2,'Server CPU'),
 (3,'Mobile CPU'),
 (4,'Heatsinks'),
 (5,'Liquid Cooling'),
 (6,'Desktop Memory'),
 (7,'Laptop Memory'),
 (8,'Mac Memory'),
 (9,'Server Memory'),
 (10,'Memory Cards'),
 (11,'AMD Motherboards'),
 (12,'Intel Motherboards'),
 (13,'Server Motherboards'),
 (14,'Desktop Graphics Cards'),
 (15,'Workstation Graphics Cards'),
 (16,'Gaming Cases'),
 (17,'Server Chassis'),
 (18,'HTPC'),
 (19,'Case Fans'),
 (20,'Case Accessories'),
 (21,'Desktop HDD'),
 (22,'Laptop HDD'),
 (23,'Mac HDD'),
 (24,'Blu Ray Burners'),
 (25,'Blu Ray Drives'),
 (26,'CD Burners'),
 (27,'CD Drives'),
 (28,'Server Power Supplies');
CREATE TABLE IF NOT EXISTS `Product` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`img`	TEXT NOT NULL,
	`price`	INTEGER NOT NULL,
	`category`	INTERGER NOT NULL,
	`subcategory`	INTERGER NOT NULL,
	FOREIGN KEY(`subcategory`) REFERENCES `Category`(`id`)
);
CREATE TABLE IF NOT EXISTS `Category` (
	`id`	INTEGER UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);
INSERT INTO `Category` (id,name) VALUES (1,'CPU'),
 (2,'Memory'),
 (3,'Motherboards'),
 (4,'Video Cards'),
 (5,'Computer Cases'),
 (6,'Power Supplies'),
 (7,'Fans'),
 (8,'Computer Accessories'),
 (9,'Barebone'),
 (10,'Server Components'),
 (11,'Sound Cards'),
 (12,'Hard Drives'),
 (13,'SSDs'),
 (14,'CD'),
 (15,'USB Flash Drives'),
 (16,'NAS');
CREATE TABLE IF NOT EXISTS `Brand` (
	`id`	INTEGER UNIQUE,
	`name`	TEXT NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);
INSERT INTO `Brand` (id,name) VALUES (1,'AMD'),
 (2,'ASUS'),
 (3,'ASRock'),
 (4,'Biostar'),
 (5,'Cooler Master'),
 (6,'Corsair'),
 (7,'DELL'),
 (8,'EVGA'),
 (9,'GIGABYTE'),
 (10,'HGST'),
 (11,'Hitachi'),
 (12,'Intel'),
 (13,'MSI'),
 (14,'NVIDIA'),
 (15,'PowerColor'),
 (16,'PNY'),
 (17,'Rosewill'),
 (18,'Sapphire'),
 (19,'Seagate'),
 (20,'SeaSonic'),
 (21,'Thermaltake'),
 (22,'Toshiba'),
 (23,'Western Digital'),
 (24,'Zotac');
COMMIT;
